spring.application.name=fashionshop

# Import local credentials if available (ignored by git)
spring.config.import=optional:classpath:application-secret.properties

# Database Configuration (Environment variable takes precedence)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/fashionshop_db}

# Cloudinary Configuration (Environment variables take precedence)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:your_cloud_name}
cloudinary.api_key=${CLOUDINARY_API_KEY:your_api_key}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:your_api_secret}
server.max-http-request-header-size=1MB
