spring.application.name=fashionshop

spring.data.mongodb.uri=mongodb://localhost:27017/fashionshop_db

cloudinary.cloud_name=duuwy6dyi
cloudinary.api_key=759598164853818
cloudinary.api_secret=2f6uZmiuZeFPgfh1iTRphOQQ2R0
server.max-http-request-header-size=1MB
spring.codec.max-in-memory-size=10MB